### ISSUE TITLE
SPARQL endpoint URI and platform URI contain hardcoded paths

### ISSUE THREAD

**Issue by cblakeley** [fusepoolP3/p3-dashboard#12]
index.html contains:
var platformURI = "http://" + host + ":8181/ldp/platform";
For Virtuoso, LDP containers are rooted under /DAV
e.g. ":8181/DAV/home/fusepool/ldp/platform"
Although we could define a virtual directory /ldp and map /DAV/home/fusepool/ldp to it, it would be better if the parent directory of platform could be made configurable.

The sparql endpoint URI passed to P3Check.initP3Platform() uses a hardcoded path '/sparql/select'. Virtuoso uses '/sparql'. Again the sparql endpoint path needs to be configurable.

**Comment by szluca** [comment]
I don't think this issue belongs to the dashboard as the gui uses URIs extracted from the platform config, it doesn't use any hardcoded URIs. (At least I couldn't find any, if you do so, pease point me to the exact file#line)

**Comment by cblakeley** [comment]
Luca, Please ignore this issue. My comments related to https://github.com/fusepoolP3/p3-platform-reference-implementation/blob/master/core/index.html. I've submitted patches to https://github.com/fusepoolP3/p3-platform-reference-implementation.
