### ISSUE TITLE
Use of <> in Turtle used by P3 Dashboard and P3 Autoconfiguration Tool without stipulating @base causes problems using Virtuoso LDP backend.

### ISSUE THREAD

**Issue by cblakeley** [fusepoolP3/p3-dashboard#13]
See https://github.com/fusepoolP3/p3-autoconfiguration-tool/issues/3

The created subject URIs use the LDP server hostname/port, not the proxy hostname/port. The Dashboard expects subject URIs to contain the latter.

**Comment by retog** [comment]
As I wrote for fusepoolP3/p3-autoconfiguration-tool#3 <> (without @base) is (unfortunately) the (only) way to refer to the resource to be created by the LDP implementation. It's ugly, it's not RDF, but if we want to go LDP we have to go down this dirty route.
