### ISSUE TITLE
Transformer configuration breaks with leading whitespace in the config

### ISSUE THREAD

**Issue by ktk** [fusepoolP3/p3-dashboard#15]
I'm not sure where this issue belongs so I post it here. I just did a demo at ICT2015 and when I copied the BatchRefine config URI from the LDP interface it seems that I copied the URI with a leading space. When I add this to the transformer factory of BatchRefine it registers a transformer _with_ the space which leads in a non-functioning transformer in the end.

It was surely my fault but I think this should be catched in the UI so it doesn't happen to others.

**Comment by szluca** [comment]
Added trimming both to the dashboard and the factory guis.
