### ISSUE TITLE
don't force user to enter configuration name on first accessing the dashboard

### ISSUE THREAD

**Issue by retog** [fusepoolP3/p3-dashboard#18]
Not sure how many users actually use the multi-profile feature, but I guess I'm not the only one who's annoied by having to enter a configuration name AND a description when first starting the dashboard. What about having "default" as default name and not presenting any dialog?

**Comment by retog** [comment]
Could you add a tag, so that a release is created? Thanks.

**Comment by szluca** [comment]
I've created a tag right after pushing this. Should I try it again?

**Comment by retog** [comment]
Oh, I'm sorry everything worked fine here. You don't need to do anything (I should trigger a build of the docker).
